#!/usr/bin/env python3

import smlib
import sys

smlib.checkEnv()
smlib.checkCLIParams()

cmd = sys.argv[1][0]

if cmd == "I": smlib.addStockItems(int(sys.argv[1][1:]))
if cmd == "S": smlib.subtractStockItems(int(sys.argv[1][1:]))
if cmd == "L": smlib.showStockAmount()
